language: rust
rust: nightly

env:
- FEATURES="std"
- FEATURES=""

script:
- cd intruder-alarm
# we have to cd into the dir rather than using cargo test -p
# since cargo test -p won't pass feature flags.
- cargo test --features=$FEATURES
- cd ..
- cargo test --features=$FEATURES