max_width = 80
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
wrap_comments = true
use_try_shorthand = true
use_field_init_shorthand = true
