[package]
name = "intruder-alarm"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
description = """
Intrusive collections for ALARM allocators.
"""

[features]
std = []
alloc = []

[dev-dependencies]
quickcheck = "0.4.1"
