[package]
name = "slabby"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
description = """
Slab allocators composable on top of ALARM memory allocators.
"""
edition = "2018"

[dependencies]
